### ISSUE TITLE
有个错别字

### ISSUE THREAD

**Issue by xiaohuazi123** [xiaoboluo768/mysql-system-schema#2]
https://github.com/xiaoboluo768/mysql-system-schema/wiki/gtid_executed
该表只在数据库初始化或者执行update_grade升级的时候创建，不允许手工创建**于**修改
改为
不允许手工创建**或**修改

最新的binlog之外其他binlog中的所有GTID**结合**记录到该表中
改为
最新的binlog之外其他binlog中的所有GTID**集合**记录到该表中

**Comment by xiaoboluo768** [comment]
收到，已修订，谢谢！
